<!DOCTYPE html>
<html lang="es">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <base href="http://www.retailcs.com/extranet/"/>

    <title>Retail Custom Solutions</title>

    <link href="./Static/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="./Static/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="./Static/build/css/custom.min.css" rel="stylesheet">
    <link href="./Static/css/retailcs.css" rel="stylesheet">

    <script src="./Static/vendors/jquery/dist/jquery.min.js"></script>
    <script src="./Static/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title">
              <a href="./" class="site_title"><img src="./Static/images/logo-small-name.png" alt=""></a>
            </div>

            <div class="clearfix"></div>
            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>Servicios</h3>
                <ul class="nav side-menu">
                  <li class="active">
                    <a><i class="fa fa-home"></i> RMS.NET <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu" style="display: block;">
                      <li><a href="javascript:void(0)" class="net-servicio" page="actualizacion" ser="rms">Actualizaciones</a></li>
                      <li><a href="javascript:void(0)" class="net-servicio" page="correccion" ser="rms">Correcciones</a></li>
                      <li><a href="javascript:void(0)" class="net-servicio" page="manual" ser="rms">Manuales</a></li>
                      <li><a href="javascript:void(0)" class="net-servicio" page="video" ser="rms">Videos</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-edit"></i> POS.NET <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="javascript:void(0)" class="net-servicio" page="actualizacion" ser="pos">Actualizaciones</a></li>
                      <li><a href="javascript:void(0)" class="net-servicio" page="correccion" ser="pos">Correcciones</a></li>
                      <li><a href="javascript:void(0)" class="net-servicio" page="manual" ser="pos">Manuales</a></li>
                      <li><a href="javascript:void(0)" class="net-servicio" page="video" ser="pos">Videos</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-desktop"></i> WMS.NET <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="javascript:void(0)" class="net-servicio" page="actualizacion" ser="wms">Actualizaciones</a></li>
                      <li><a href="javascript:void(0)" class="net-servicio" page="correccion" ser="wms">Correcciones</a></li>
                      <li><a href="javascript:void(0)" class="net-servicio" page="manual" ser="wms">Manuales</a></li>
                      <li><a href="javascript:void(0)" class="net-servicio" page="video" ser="wms">Videos</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-bug"></i> POLLING <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="javascript:void(0)" class="net-servicio" page="actualizacion" ser="polling">Actualizaciones</a></li>
                      <li><a href="javascript:void(0)" class="net-servicio" page="correccion" ser="polling">Correcciones</a></li>
                      <li><a href="javascript:void(0)" class="net-servicio" page="manual" ser="polling">Manuales</a></li>
                      <li><a href="javascript:void(0)" class="net-servicio" page="video" ser="polling">Videos</a></li>
                    </ul>
                  </li>
                </ul>
              </div>

              <div class="menu_section">
                <h3>Otros</h3>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-bug"></i> Redes Sociales <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="javascript:void(0)" class="redes-sociales">Facebook</a></li>
                      <li><a href="javascript:void(0)" class="redes-sociales">Twitter</a></li>
                      <li><a href="javascript:void(0)" class="redes-sociales">Instagram</a></li>
                      <li><a href="javascript:void(0)" class="redes-sociales">Youtube</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
              
              <?php if ($_SESSION['User']['Type'] == 1) { ?>
              <div class="menu_section">
                <h3>Admin</h3>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-bug"></i> Gestión Usuarios <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="javascript:void(0)" class="gestion-admin">Nuevo Usuario</a></li>
                      <li><a href="javascript:void(0)" class="gestion-admin">Lista Usuarios</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
              <?php } ?>

            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Logout" href="./login/cerrarSession/">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <?php echo $_SESSION['User']['Business']; ?> <span class=" fa fa-angle-down"></span>
                  </a>
                  <!--<a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="images/img.jpg" alt="">John Doe
                    <span class=" fa fa-angle-down"></span>
                  </a>-->
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <!--
                    <li><a href="javascript:;"> Profile</a></li>                    
                    <li>
                      <a href="javascript:;">
                        <span class="badge bg-red pull-right">50%</span>
                        <span>Settings</span>
                      </a>
                    </li>
                    -->
                    <li><a href="javascript:void(0)">Ayuda</a></li>
                    <li><a href="./login/cerrarSession/"><i class="fa fa-sign-out pull-right"></i> Cerrar Sesión</a></li>
                  </ul>
                </li>

                <li role="presentation" class="dropdown">
                  <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-envelope-o"></i>
                    <span class="badge bg-green">6</span>
                  </a>
                  <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                    <li>
                      <a>
                        <span class="image"><img src="https://colorlib.com/polygon/gentelella/images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="https://colorlib.com/polygon/gentelella/images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          <div class="row">

            <div id="principal">
              <?php
                echo $page;
              ?>
            </div>

          </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Retail Custom Solutions
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div> 

    <script src="./Static/build/js/custom.min.js"></script>
    <script src="./Static/js/retailcs.js"></script>

  </body>
</html>
