<!DOCTYPE html>
<html lang="es">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <base href="<?php echo HTTP_HOST; ?>"/>

    <title>Retail Custom Solutions</title>
    <link rel="shortcut icon" href="http://www.retailcs.com/es/public/img/favicon.ico">
    <!-- Bootstrap -->
    <link href="./Static/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="./Static/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- Datatables -->
    <link href="./Static/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="./Static/build/css/custom.min.css" rel="stylesheet">
    <link href="./Static/css/retailcs.css" rel="stylesheet">

  </head>
  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title">
              <a href="./" class="site_title"><img id="logo-retailcs" class="logo-small" src="./Static/images/logo-small-name.png" alt="Retail Custom Solutions"></a>
            </div>
            <div class="clearfix"></div>
            <br/>

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>Servicios</h3>
                <ul class="nav side-menu" id="menu-product">
                  
                  <?php echo $menu_product; ?>
                
                </ul>
              </div>
              
              <?php if ($_SESSION['User']['Type'] == 1) { ?>
              <div class="menu_section">
                <h3>Admin</h3>
                <ul class="nav side-menu" id="menu-admin">

                  <?php echo $menu_admin; ?>
                  
                </ul>
              </div>
              <?php } ?>

            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <!--<div class="sidebar-footer hidden-small">
              <a href="https://www.facebook.com/RetailCS" target="_blank" data-toggle="tooltip" data-placement="top" title="Facebook">
                <span class="fa fa-facebook-square" aria-hidden="true"></span>
              </a>
              <a href="https://twitter.com/SalesRCS" target="_blank" data-toggle="tooltip" data-placement="top" title="Twitter">
                <span class="fa fa-twitter-square" aria-hidden="true"></span>
              </a>
              <a href="https://www.linkedin.com/company/retail-custom-solutions" target="_blank" data-toggle="tooltip" data-placement="top" title="Linkedin">
                <span class="fa fa-linkedin-square" aria-hidden="true"></span>
              </a>
              <a href="https://www.youtube.com/channel/" target="_blank" data-toggle="tooltip" data-placement="top" title="Youtube">
                <span class="fa fa-youtube" aria-hidden="true"></span>
              </a>
            </div>-->
            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="Static/images/img.png" alt="">
                    <?php echo $_SESSION['User']['Name']; ?> <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <!--
                    <li><a href="javascript:void(0);"> <strong>RETAIL</strong></a></li>                    
                    <li>
                      <a href="javascript:;">
                        <span class="badge bg-red pull-right">50%</span>
                        <span>Settings</span>
                      </a>
                    </li>
                    -->
                    <li><a href="javascript:void(0);">Ayuda</a></li>
                    <li><a href="javascript:void(0);" id="logout"><i class="fa fa-sign-out pull-right"></i> Cerrar Sesión</a></li>
                  </ul>
                </li>


                <li role="redes-sociales" class="redes-sociales">
                  <div class="product_social">
                    <ul class="list-inline">
                      <li>
                        <a href="https://www.youtube.com/channel/" target="_blank" data-toggle="tooltip" data-placement="bottom" title="Youtube">
                          <!--<i class="fa fa-youtube"></i>-->
                          <img src="./Static/images/socials-network/youtube.png" alt="Youtube">
                        </a>
                      </li>
                      <li>
                        <a href="https://www.linkedin.com/company/retail-custom-solutions" target="_blank" data-toggle="tooltip" data-placement="bottom" title="Linkedin">
                          <!--<i class="fa fa-linkedin-square"></i>-->
                          <img src="./Static/images/socials-network/linkedin.png" alt="Linkedin">
                        </a>
                      </li>
                      <li>
                        <a href="https://twitter.com/SalesRCS" target="_blank" data-toggle="tooltip" data-placement="bottom" title="Twitter">
                          <!--<i class="fa fa-twitter-square"></i>-->
                          <img src="./Static/images/socials-network/twitter.png" alt="Twitter">
                        </a>
                      </li>
                      <li>
                        <a href="https://www.facebook.com/RetailCS" target="_blank" data-toggle="tooltip" data-placement="bottom" title="Facebook">
                          <!--<i class="fa fa-facebook-square"></i>-->
                          <img src="./Static/images/socials-network/facebook.png" alt="Facebook">
                        </a>
                      </li>
                    </ul>
                  </div>
                </li>

                <!--
                <li role="presentation" class="dropdown">
                  <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-envelope-o"></i>
                    <span class="badge bg-green">6</span>
                  </a>
                  <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                    <li>
                      <a>
                        <span class="image"><img src="https://colorlib.com/polygon/gentelella/images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="https://colorlib.com/polygon/gentelella/images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                  </ul>
                </li>
                -->
  
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          <div class="row">

            <div id="principal">
              <?php
                echo $page;
              ?>
            </div>

          </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Retail Custom Solutions
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div> 

    <!-- jQuery -->
    <script src="./Static/vendors/jquery/dist/jquery.min.js"></script>
    <script src="./Static/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- Datatables -->
    <script src="./Static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="./Static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <!-- Custom Theme Scripts -->
    <script src="./Static/build/js/custom.min.js"></script>
    <script src="./Static/js/retailcs.js"></script>

  </body>
</html>
