<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Retail Custom Solutions</title>

    <link href="../Static/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="../Static/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="../Static/build/css/custom.min.css" rel="stylesheet">

  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <!-- page content -->
        <div class="col-md-12">
          <div class="col-middle">
            <div class="text-center text-center">
              <h1 class="error-number">403</h1>
              <h2>Acceso denegado</h2>
              <p>Se requiere autenticación completa para acceder a este recurso. <a href="#">¿Reporta esto?</a>
              </p>
              <div class="mid_center">
                <h3>Buscar</h3>
                <form>
                  <div class="col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                      <input type="text" class="form-control" placeholder="Buscar...">
                      <span class="input-group-btn">
                              <button class="btn btn-default" type="button">¡Ir!</button>
                          </span>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->
      </div>
    </div>

    <script src="../Static/vendors/jquery/dist/jquery.min.js"></script>
    <script src="../Static/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="../Static/build/js/custom.min.js"></script>

  </body>
</html>