<!DOCTYPE html>
<html lang="es">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Retail Custom Solutions</title>
    <link rel="shortcut icon" href="http://www.retailcs.com/es/public/img/favicon.ico">
    <!-- Bootstrap -->
    <link href="http://www.retailcs.com/apps/extranet/Static/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://www.retailcs.com/apps/extranet/Static/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- Datatables -->
    <link href="http://www.retailcs.com/apps/extranet/Static/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="http://www.retailcs.com/apps/extranet/Static/build/css/custom.min.css" rel="stylesheet">
    <link href="http://www.retailcs.com/apps/extranet/Static/css/retailcs.css" rel="stylesheet">

  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <!-- page content -->
        <div class="col-md-12">
          <div class="col-middle">
            <div class="text-center">
              <h1 class="error-number">500</h1>
              <h2>Error interno del servidor</h2>
              <p>Seguimos estos errores automáticamente, pero si el problema persiste no dude en ponerse en contacto con nosotros. Mientras tanto, trate de refrescar. <a href="#">¿Reporta esto?</a></p>
              <div class="mid_center">
                <p>
                  <a href="http://www.retailcs.com/apps/extranet/">
                    <img src="http://www.retailcs.com/apps/extranet/Static/images/pagehome.png" alt="Retail Custom Solution - Extranet" width="96px">
                    <br><br>
                    Ir a la página principal!
                  </a>
                </p>
                <!--
                <h3>Buscar</h3>
                <form>
                  <div class="col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                      <input type="text" class="form-control" placeholder="Buscar...">
                      <span class="input-group-btn">
                              <button class="btn btn-default" type="button">¡Ir!</button>
                          </span>
                    </div>
                  </div>
                </form>
                -->
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->
      </div>
    </div>

    <script src="http://www.retailcs.com/apps/extranet/Static/vendors/jquery/dist/jquery.min.js"></script>
    <script src="http://www.retailcs.com/apps/extranet/Static/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="http://www.retailcs.com/apps/extranet/Static/build/js/custom.min.js"></script>

  </body>
</html>