<?php
	
	$product = $object_product['ObjectProduct']['Product'];
	$content_type = $object_product['ObjectProduct']['ContentType'];
	$array_version = $object_product['ObjectProduct']['ObjectVersion'];

	$estado = 0;
	foreach ($array_version as $key => $value) {
		if (count($value['ContentDetail']) > 0) {
			$estado = 1;
		}
	}

?>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<blockquote>
				<p class="title"><?php if($_SESSION['Business']['Language']=='en'){ echo $content_type->content_description_en; } else { echo $content_type->content_description; } ?></p>
				<div class="subtitle"><?php echo $product->product_name; ?></div>
			</blockquote>
		</div>
	</div>

	<div class="clearfix"></div>

	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">

			<?php
			if ($estado) {
				foreach ($array_version as $key_v => $value_v) {
					$version = $value_v['Version'];
					$content = $value_v['Content'];
					$content_detail = $value_v['ContentDetail'];
					
					if (isset($version)) {
						if (isset($content)) {
							if (isset($content_detail)) {
			?>

			<!-- Inicio - Table Collapse 1 -->
			<div class="x_panel">
				<div class="x_title">
					<h2><span class="lang-span-version">Version</span> <?php echo $version->version_description; ?><small>/ <span class="lang-span-update">Updated the</span>: <?php echo formatDayDate($content->publication_date); ?></small></h2>
					<ul class="nav navbar-right panel_toolbox">
						<li><a class="collapse-link"><i class="fa fa-bars"></i> <span class="lang-span-all">View All</span></a></li>
					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="x_content" <?php ($key_v==0? '': 'style="display: none;"') ?> >
					<table class="table table-striped table-actualizacion">
						<thead>
							<tr>
								<th class="lang-th-no" width="10%">N°</th>
								<th class="lang-th-date" width="15%">Date</th>
								<th class="lang-th-description" width="75%">Description</th>
							</tr>
						</thead>
						<tbody>

							<?php
							foreach ($content_detail as $key_cd => $value_cd) {
							?>

							<tr>
								<th scope="row"><?php echo $key_cd+1; ?></th>
								<td><?php echo formatDate($value_cd->registry_date); ?></td>
								<td><?php if($_SESSION['Business']['Language']=='en'){ echo utf8_encode($value_cd->detail_description_en); } else { echo utf8_encode($value_cd->detail_description); } ?></td>
							</tr>

							<?php
							}
							?>

						</tbody>
					</table>					
					<div class="actionBar">
						<a href="javascript:void(0)" idcontent="<?php echo $content->idcontent; ?>" language="<?php echo $_SESSION['Business']['Language']; ?>" description="<?php if($_SESSION['Business']['Language']=='en'){ echo $content_type->content_description_en; } else { echo $content_type->content_description; } ?>" product="<?php echo $product->product_name; ?>" version="<?php echo $version->version_description; ?>" type="button" class="btn btn-primary download-content"><i class="fa fa-download"></i> <span class="lang-button-download-pdf">Download PDF</span></a>
					</div>
				</div>
			</div>
			<!-- Fin - Table Collapse 1 -->
			
			<?php
							}
						}
					}
				} 
			} else {
			?>

			<div class="x_panel">
				No hay actualizaciones...
			</div>
			
			<?php
			}
			?>
			
		</div>
		<div class="clearfix"></div>		
	</div>
	<div class="clearfix"></div>
</div>