<?php 
	/*echo $pagina;*/
	$servicio = $servicio.'.net';
?>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<blockquote>
				<p>Actualizaciones</p>
				<div class="subtitle"><?php echo $servicio; ?></div>
			</blockquote>
		</div>
	</div>

	<div class="clearfix"></div>

	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">

			<!-- Inicio - Table Collapse 1 -->
			<div class="x_panel">
				<div class="x_title">
					<h2>Versión 9.00 <small>/ Actualizado el: Viernes 10, 2017</small></h2>
					<ul class="nav navbar-right panel_toolbox">
						<li><a class="collapse-link"><i class="fa fa-bars"></i> Ver Todo</a></li>
						<!--<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="#">Settings 1</a></li>
								<li><a href="#">Settings 2</a></li>
							</ul>
						</li>-->
						<!--<li><a class="close-link"><i class="fa fa-close"></i></a></li>-->
					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="x_content">
					<table class="table table-striped">
						<thead>
							<tr>
								<th>#</th>
								<th>Fecha</th>
								<th>Descripción</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<th scope="row">362</th>
								<td>08-02-2017</td>
								<td>when copying a PO to an Invoice it was calculating wrong the Qty Order</td>
							</tr>
							<tr>
								<th scope="row">361</th>
								<td>07-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">360</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">359</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">358</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">357</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">356</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
						</tbody>
					</table>

					<div class="actionBar">
						<a href="javascript:void(0)" type="button" class="btn btn-primary"><i class="fa fa-download"></i> Descargar en PDF</a>
					</div>
				</div>
			</div>
			<!-- Fin - Table Collapse 1 -->


			<!-- Inicio - Table Collapse 2 -->
			<div class="x_panel">
				<div class="x_title">
					<h2>Versión 8.00 <small>/ Actualizado el: Miércoles 27, 2016</small></h2>
					<ul class="nav navbar-right panel_toolbox">
						<li><a class="collapse-link"><i class="fa fa-bars"></i> Ver Todo</a></li>
						<!--<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="#">Settings 1</a></li>
								<li><a href="#">Settings 2</a></li>
							</ul>
						</li>-->
						<!--<li><a class="close-link"><i class="fa fa-close"></i></a></li>-->
					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="x_content" style="display: none;">
					<table class="table table-striped">
						<thead>
							<tr>
								<th>#</th>
								<th>Fecha</th>
								<th>Descripción</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<th scope="row">362</th>
								<td>08-02-2017</td>
								<td>when copying a PO to an Invoice it was calculating wrong the Qty Order</td>
							</tr>
							<tr>
								<th scope="row">361</th>
								<td>07-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">360</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">359</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">358</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">357</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">356</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
						</tbody>
					</table>
					
					<div class="actionBar">
						<a href="javascript:void(0)" type="button" class="btn btn-primary"><i class="fa fa-download"></i> Descargar en PDF</a>
					</div>
				</div>
			</div>
			<!-- Fin - Table Collapse 2 -->


			<!-- Inicio - Table Collapse 3 -->
			<div class="x_panel">
				<div class="x_title">
					<h2>Versión 7.00 <small>/ Actualizado el: Lunes 15, 2015</small></h2>
					<ul class="nav navbar-right panel_toolbox">
						<li><a class="collapse-link"><i class="fa fa-bars"></i> Ver Todo</a></li>
						<!--<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="#">Settings 1</a></li>
								<li><a href="#">Settings 2</a></li>
							</ul>
						</li>-->
						<!--<li><a class="close-link"><i class="fa fa-close"></i></a></li>-->
					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="x_content" style="display: none;">
					<table class="table table-striped">
						<thead>
							<tr>
								<th>#</th>
								<th>Fecha</th>
								<th>Descripción</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<th scope="row">362</th>
								<td>08-02-2017</td>
								<td>when copying a PO to an Invoice it was calculating wrong the Qty Order</td>
							</tr>
							<tr>
								<th scope="row">361</th>
								<td>07-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">360</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">359</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">358</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">357</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">356</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
						</tbody>
					</table>
					
					<div class="actionBar">
						<a href="javascript:void(0)" type="button" class="btn btn-primary"><i class="fa fa-download"></i> Descargar en PDF</a>
					</div>
				</div>
			</div>
			<!-- Fin - Table Collapse 3 -->


			<!-- Inicio - Table Collapse 3 -->
			<div class="x_panel">
				<div class="x_title">
					<h2>Versión 6.00 <small>/ Actualizado el: Lunes 15, 2014</small></h2>
					<ul class="nav navbar-right panel_toolbox">
						<li><a class="collapse-link"><i class="fa fa-bars"></i> Ver Todo</a></li>
						<!--<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="#">Settings 1</a></li>
								<li><a href="#">Settings 2</a></li>
							</ul>
						</li>-->
						<!--<li><a class="close-link"><i class="fa fa-close"></i></a></li>-->
					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="x_content" style="display: none;">
					<table class="table table-striped">
						<thead>
							<tr>
								<th>#</th>
								<th>Fecha</th>
								<th>Descripción</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<th scope="row">362</th>
								<td>08-02-2017</td>
								<td>when copying a PO to an Invoice it was calculating wrong the Qty Order</td>
							</tr>
							<tr>
								<th scope="row">361</th>
								<td>07-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">360</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">359</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">358</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">357</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">356</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
						</tbody>
					</table>
					
					<div class="actionBar">
						<a href="javascript:void(0)" type="button" class="btn btn-primary"><i class="fa fa-download"></i> Descargar en PDF</a>
					</div>
				</div>
			</div>
			<!-- Fin - Table Collapse 3 -->


			<!-- Inicio - Table Collapse 3 -->
			<div class="x_panel">
				<div class="x_title">
					<h2>Versión 5.00 <small>/ Actualizado el: Lunes 15, 2013</small></h2>
					<ul class="nav navbar-right panel_toolbox">
						<li><a class="collapse-link"><i class="fa fa-bars"></i> Ver Todo</a></li>
						<!--<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="#">Settings 1</a></li>
								<li><a href="#">Settings 2</a></li>
							</ul>
						</li>-->
						<!--<li><a class="close-link"><i class="fa fa-close"></i></a></li>-->
					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="x_content" style="display: none;">
					<table class="table table-striped">
						<thead>
							<tr>
								<th>#</th>
								<th>Fecha</th>
								<th>Descripción</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<th scope="row">362</th>
								<td>08-02-2017</td>
								<td>when copying a PO to an Invoice it was calculating wrong the Qty Order</td>
							</tr>
							<tr>
								<th scope="row">361</th>
								<td>07-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">360</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">359</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">358</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">357</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
							<tr>
								<th scope="row">356</th>
								<td>06-02-2017</td>
								<td>when copying a Sales Order from History Grid and change the Store then Save the Order, it throws an exception message</td>
							</tr>
						</tbody>
					</table>
					
					<div class="actionBar">
						<a href="javascript:void(0)" type="button" class="btn btn-primary"><i class="fa fa-download"></i> Descargar en PDF</a>
					</div>
				</div>
			</div>
			<!-- Fin - Table Collapse 3 -->			

		</div>
		<div class="clearfix"></div>		
	</div>

	<div class="clearfix"></div>
	
</div>