<div class="container info-reciente">
	<div class="row">
		<div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><span class="lang-h2-welcome">Welcome</span> <?php echo $user; ?><small class="lang-small-information-recent">Recent information...</small></h2>
                    <div class="clearfix"></div>
                </div>
            </div>
      
            <div class="x_content">
                <div class="row">

                    <?php echo $info_recent; ?>
                    
                </div>
            </div>      
		</div>
	</div>
</div>