<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Retail Custom Solutions</title>

    <!-- Bootstrap -->
    <link href="../Static/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="../Static/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="../Static/build/css/custom.min.css" rel="stylesheet">
    <link href="../Static/css/login.css" rel="stylesheet">
  </head>

  <body class="login">
    <a class="hiddenanchor" id="signup"></a>
    <a class="hiddenanchor" id="signin"></a>

    <div class="login_wrapper">
      <div class="animate login_form">
        <section class="login_content">
          <form class="flex-container">
            <section class="flex-item">
              <div></div>
            </section>
            <section class="flex-item form-item">
              <div class="form">
                <div class="form-group">
                  <input type="text" id="usuario" class="form-control" placeholder="Usuario" required="" />
                </div>
                <div class="form-group">
                  <input type="password" id="contrasena" class="form-control" placeholder="Contraseña" required="" />
                  <span class="glyphicon glyphicon-eye-open form-control-feedback" aria-hidden="true"></span>
                </div>
                <div class="form-group">
                  <btn class="btn btn-block btn-default submit"id="login-ingresar">Ingresar</btn>
                </div>
                <div class="form-group">
                  <btn class="reset_pass">¿Olvidó su contraseña?</btn>
                </div>
              </div>                
            </section>
            <section class="flex-item">
              <div class="author">
                <div class="clearfix"></div>
                <div>
                  <h5>Desarrollado por:</h5>
                  <p><img src="../Static/images/logo-small-name-black.png" alt=""></p>
                </div>
              </div>
            </section>               
          </form>
        </section>
      </div>

      <div id="register" class="animate form registration_form">
        <section class="login_content">
          <form>
            <h1>Crer Cuenta</h1>
            <div>
              <input type="text" class="form-control" placeholder="Usuario" required="" />
            </div>
            <div>
              <input type="email" class="form-control" placeholder="Email" required="" />
            </div>
            <div>
              <input type="password" class="form-control" placeholder="Contraseña" required="" />
            </div>
            <div>
              <a class="btn btn-default submit" href="../">Enviar</a>
            </div>

            <div class="clearfix"></div>

            <div class="separator">
              <!--<p class="change_link">Already a member ?
                <a href="#signin" class="to_register"> Log in </a>
              </p>-->
              <div class="clearfix"></div>
              <div>
                <!--<h1><i class="fa fa-paw"></i> Desarrollado por:</h1>-->
                <h5>Desarrollado por:</h5>
                <p><img src="../Static/images/logo-small-name-black.png" alt=""></p>
              </div>
            </div>
          </form>
        </section>
      </div>
    </div>

    <script src="../Static/vendors/jquery/dist/jquery.min.js"></script>
    <script src="../Static/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="../Static/js/login.js"></script>

  </body>
</html>
