<?php 
	/*echo $pagina;*/
	$servicio = $servicio.'.net';
?>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<blockquote>
				<p>Manuales</p>
				<div class="subtitle"><?php echo $servicio; ?></div>
			</blockquote>
		</div>
	</div>

	<div class="clearfix"></div>

	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
		
			<!-- Inicio - Table Collapse 1 -->
			<div class="x_panel">
				<div class="x_title">
					<h2>&nbsp;<small>&nbsp;</small></h2>
					<ul class="nav navbar-right panel_toolbox">
						<li><a class="collapse-list"><i class="glyphicon glyphicon-th-list"></i> Ver Modo Lista</a></li>
						<li><a class="collapse-grilla"><i class="glyphicon glyphicon-th"></i> Ver Modo Grilla</a></li>
					</ul>
					<div class="clearfix"></div>
				</div>

				<div class="x_content">
					<div class="row">

						<!-- Inicio - Grilla - Lista -->

						<div class="col-md-55">
							<div class="thumbnail">
								<div class="image view view-list">
									<img class="img-manual" src="./extranet/Static/images/pdf-icon.png" alt="image" />
								</div>
								<div class="caption">
									<div class="caption-left">
										<p><strong>Como inicializar información con <?php echo $servicio; ?></strong></p>
										<p>Publicado el 02/02/2017 <br class="br-list"> 5MB</p>
									</div>
									<div class="caption-right">
										<p><a href="http://www.uv.es/vguillem/Laleydelamor.pdf" download="Manual2017" type="button" class="btn btn-primary"><i class="fa fa-download"></i> Descargar</a></p>	
									</div>
									<div class="clearfix"></div>								
								</div>
							</div>
						</div>

						<div class="col-md-55 col-md-55-list">
							<div class="thumbnail">
								<div class="image view view-list">
									<img class="img-manual" src="./extranet/Static/images/pdf-icon.png" alt="image" />
								</div>
								<div class="caption">
									<div class="caption-left">
										<p><strong>Como inicializar información con <?php echo $servicio; ?></strong></p>
										<p>Publicado el 02/02/2017 <br class="br-list"> 5MB</p>
									</div>
									<div class="caption-right">
										<p><a href="http://www.uv.es/vguillem/Laleydelamor.pdf" download="Manual2017" type="button" class="btn btn-primary"><i class="fa fa-download"></i> Descargar</a></p>	
									</div>
									<div class="clearfix"></div>
								</div>
							</div>
						</div>

						<div class="col-md-55 col-md-55-list">
							<div class="thumbnail">
								<div class="image view view-list">
									<img class="img-manual" src="./extranet/Static/images/pdf-icon.png" alt="image" />
								</div>
								<div class="caption">
									<div class="caption-left">
										<p><strong>Como inicializar información con <?php echo $servicio; ?></strong></p>
										<p>Publicado el 02/02/2017 <br class="br-list"> 5MB</p>
									</div>
									<div class="caption-right">
										<p><a href="http://www.uv.es/vguillem/Laleydelamor.pdf" download="Manual2017" type="button" class="btn btn-primary"><i class="fa fa-download"></i> Descargar</a></p>	
									</div>
									<div class="clearfix"></div>
								</div>
							</div>
						</div>

						<div class="col-md-55 col-md-55-list">
							<div class="thumbnail">
								<div class="image view view-list">
									<img class="img-manual" src="./extranet/Static/images/pdf-icon.png" alt="image" />
								</div>
								<div class="caption">
									<div class="caption-left">
										<p><strong>Como inicializar información con <?php echo $servicio; ?></strong></p>
										<p>Publicado el 02/02/2017 <br class="br-list"> 5MB</p>
									</div>
									<div class="caption-right">
										<p><a href="http://www.uv.es/vguillem/Laleydelamor.pdf" download="Manual2017" type="button" class="btn btn-primary"><i class="fa fa-download"></i> Descargar</a></p>	
									</div>
									<div class="clearfix"></div>
								</div>
							</div>
						</div>

						<div class="col-md-55 col-md-55-list">
							<div class="thumbnail">
								<div class="image view view-list">
									<img class="img-manual" src="./extranet/Static/images/pdf-icon.png" alt="image" />
								</div>
								<div class="caption">
									<div class="caption-left">
										<p><strong>Como inicializar información con <?php echo $servicio; ?></strong></p>
										<p>Publicado el 02/02/2017 <br class="br-list"> 5MB</p>
									</div>
									<div class="caption-right">
										<p><a href="http://www.uv.es/vguillem/Laleydelamor.pdf" download="Manual2017" type="button" class="btn btn-primary"><i class="fa fa-download"></i> Descargar</a></p>	
									</div>
									<div class="clearfix"></div>
								</div>
							</div>
						</div>

						<div class="col-md-55 col-md-55-list">
							<div class="thumbnail">
								<div class="image view view-list">
									<img class="img-manual" src="./extranet/Static/images/pdf-icon.png" alt="image" />
								</div>
								<div class="caption">
									<div class="caption-left">
										<p><strong>Como inicializar información con <?php echo $servicio; ?></strong></p>
										<p>Publicado el 02/02/2017 <br class="br-list"> 5MB</p>
									</div>
									<div class="caption-right">
										<p><a href="http://www.uv.es/vguillem/Laleydelamor.pdf" download="Manual2017" type="button" class="btn btn-primary"><i class="fa fa-download"></i> Descargar</a></p>	
									</div>
									<div class="clearfix"></div>
								</div>
							</div>
						</div>

						<div class="col-md-55 col-md-55-list">
							<div class="thumbnail">
								<div class="image view view-list">
									<img class="img-manual" src="./extranet/Static/images/pdf-icon.png" alt="image" />
								</div>
								<div class="caption">
									<div class="caption-left">
										<p><strong>Como inicializar información con <?php echo $servicio; ?></strong></p>
										<p>Publicado el 02/02/2017 <br class="br-list"> 5MB</p>
									</div>
									<div class="caption-right">
										<p><a href="http://www.uv.es/vguillem/Laleydelamor.pdf" download="Manual2017" type="button" class="btn btn-primary"><i class="fa fa-download"></i> Descargar</a></p>	
									</div>
									<div class="clearfix"></div>
								</div>
							</div>
						</div>

						<div class="col-md-55 col-md-55-list">
							<div class="thumbnail">
								<div class="image view view-list">
									<img class="img-manual" src="./extranet/Static/images/pdf-icon.png" alt="image" />
								</div>
								<div class="caption">
									<div class="caption-left">
										<p><strong>Como inicializar información con <?php echo $servicio; ?></strong></p>
										<p>Publicado el 02/02/2017 <br class="br-list"> 5MB</p>
									</div>
									<div class="caption-right">
										<p><a href="http://www.uv.es/vguillem/Laleydelamor.pdf" download="Manual2017" type="button" class="btn btn-primary"><i class="fa fa-download"></i> Descargar</a></p>	
									</div>
									<div class="clearfix"></div>
								</div>
							</div>
						</div>

						<div class="col-md-55 col-md-55-list">
							<div class="thumbnail">
								<div class="image view view-list">
									<img class="img-manual" src="./extranet/Static/images/pdf-icon.png" alt="image" />
								</div>
								<div class="caption">
									<div class="caption-left">
										<p><strong>Como inicializar información con <?php echo $servicio; ?></strong></p>
										<p>Publicado el 02/02/2017 <br class="br-list"> 5MB</p>
									</div>
									<div class="caption-right">
										<p><a href="http://www.uv.es/vguillem/Laleydelamor.pdf" download="Manual2017" type="button" class="btn btn-primary"><i class="fa fa-download"></i> Descargar</a></p>	
									</div>
									<div class="clearfix"></div>
								</div>
							</div>
						</div>

						<div class="col-md-55 col-md-55-list">
							<div class="thumbnail">
								<div class="image view view-list">
									<img class="img-manual" src="./extranet/Static/images/pdf-icon.png" alt="image" />
								</div>
								<div class="caption">
									<div class="caption-left">
										<p><strong>Como inicializar información con <?php echo $servicio; ?></strong></p>
										<p>Publicado el 02/02/2017 <br class="br-list"> 5MB</p>
									</div>
									<div class="caption-right">
										<p><a href="http://www.uv.es/vguillem/Laleydelamor.pdf" download="Manual2017" type="button" class="btn btn-primary"><i class="fa fa-download"></i> Descargar</a></p>	
									</div>
									<div class="clearfix"></div>
								</div>
							</div>
						</div>
						<!-- Fin - Grilla - Lista -->
					
					</div>
				</div>
			</div>
		</div>	
	</div>
	<div class="clearfix"></div>

</div>