<?php

	//echo '<pre>';
	//var_dump($array_result_content);
	//echo '</pre>';

	header("Content-type: application/vnd.ms-excel; name='excel'");
	header("Content-Disposition: filename=ficheroExcel.xls");
	header("Pragma: no-cache");
	header("Expires: 0");

?>


<table width="50%" border="1" cellpadding="10" cellspacing="0" bordercolor="#666666" id="Exportar_a_Excel" style="border-collapse:collapse;">
   <tr>
      <td>Celda1</td>
      <td>Celda2</td>
      <td>Celda3</td>
      <td>Celda4</td>
      <td>Celda5</td>
   </tr>
   <tr>
      <td>Celda6</td>
      <td>Celda7</td>
      <td>Celda8</td>
      <td>Celda9</td>
      <td>Celda10</td>
   </tr>
</table>