<?php

	if (isset($pagina)) {
		$tipo = 0;
		if ($seccion == 'nuevo') { $tipo = 1; }
		if ($seccion == 'tipo') { $tipo = 2; }
		if ($seccion == 'lista') { $tipo = 3; }
	}

?>

<div class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">

			<!-- Inicio - Menajes de Alerta -->
      		<div id="div-alert" class="x_content bs-example-popovers">
        		<!-- class="alert-success ó alert-info ó alert-warning ó alert-danger" -->
				<div id="div-message" class="alert alert-info alert-dismissible fade in" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
					<span class="text-message"><strong>Hola mundo!</strong> Sonríe la vida es bella... ^_^</span>
				</div>
      		</div>
      		<!-- Fin - Menajes de Alerta -->

      		<?php if($tipo == 1){ ?>

			<div class="x_panel">
				<div class="x_title">
					<h2>Nuevo usuario <small>Complete los campos</small></h2>
					<ul class="nav navbar-right panel_toolbox">
						<li class="chevron-up-right">
							<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
						</li>
						<!--<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="#">Settings 1</a></li>
								<li><a href="#">Settings 2</a></li>
							</ul>
						</li>
						<li><a class="close-link"><i class="fa fa-close"></i></a></li>-->
					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="x_content">
					<form id="form-user" class="form-horizontal form-label-left">
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="user-name">Nombre Usuario <span class="required">*</span></label>
							<div class="col-md-6 col-sm-6 col-xs-12">
								<input type="text" id="user-name" name="user-name" required="required" placeholder="ej. fcabezasr" class="form-control col-md-7 col-xs-12">
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="password">Contraseña <span class="required">*</span></label>
							<div class="col-md-6 col-sm-6 col-xs-12">
								<input type="password" id="password" name="password" required="required" class="form-control col-md-7 col-xs-12">
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="repeat-password">Repita Contraseña <span class="required">*</span></label>
							<div class="col-md-6 col-sm-6 col-xs-12">
								<input type="password" id="repeat-password" name="repeat-password" required="required" class="form-control col-md-7 col-xs-12">
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="business-name">Empresa <span class="required">*</span></label>
							<div class="col-md-6 col-sm-6 col-xs-12">
								<select id="business-name" name="business-name" class="form-control" required="required">
		                            <option value="">-- Seleccione --</option>
		                            <?php echo $listBusiness; ?>
	                          	</select>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="type-user">Tipo Usuario <span class="required">*</span></label>
							<div class="col-md-6 col-sm-6 col-xs-12">
								<select id="type-user" name="type-user" class="form-control" required="required">
		                            <option value="">-- Seleccione --</option>
		                            <?php echo $listTypeUser; ?>
	                          	</select>
							</div>
						</div>
						<div class="ln_solid"></div>
						<div class="form-group">
							<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
								<button class="btn btn-primary" id="btn-reset-user" type="reset">Limpiar</button>
								<button class="btn btn-success" id="btn-guardar-user" type="button">Guardar</button>
							</div>
						</div>
					</form>
				</div>
			</div>

			<div class="x_panel">
				<div class="x_title">
					<h2>Lista de usuarios <small>&nbsp;</small></h2>
					<ul class="nav navbar-right panel_toolbox">
						<li class="chevron-up-right">
							<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
						</li>
					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="x_content">					
					<table id="table-user" class="table table-striped table-bordered" cellspacing="0" width="100%">
				        <thead>
				            <tr>
				                <th>N°</th>
				                <th>Usuario</th>
				                <th>Tipo</th>
				                <th>Empresa</th>
				                <th>Fecha Registro</th>
				                <th>Estado</th>
				                <th>Acciones</th>
				            </tr>
				        </thead>
				        <tbody>
				            <tr>
				                <td class="td-center">1</td>
				                <td class="td-center">Tiger</td>
				                <td class="td-center">Architect</td>
				                <td class="td-center">Retailcs</td>
				                <td class="td-center">2011/04/25</td>
				                <td class="td-center">Habilitado</td>
				                <td class="td-center">
									<button class="btn btn-default" id="" type="button"><i class="glyphicon glyphicon-pencil"></i></button>
				                	<button class="btn btn-default" id="" type="button"><i class="glyphicon glyphicon-remove"></i></button>
				                </td>
				            </tr>
				            <tr>
				                <td class="td-center">2</td>
				                <td class="td-center">Tiger</td>
				                <td class="td-center">Architect</td>
				                <td class="td-center">Retailcs</td>
				                <td class="td-center">2011/04/25</td>
				                <td class="td-center">Deshabilitado</td>
				                <td class="td-center">
									<button class="btn btn-default" id="" type="button"><i class="glyphicon glyphicon-pencil"></i></button>
				                	<button class="btn btn-default" id="" type="button"><i class="glyphicon glyphicon-remove"></i></button>
				                </td>
				            </tr>
				        </tbody>
				    </table>
					<script>
					  	$(document).ready(function() {
							$('#table-user').DataTable();
					  	});
					</script>
				</div>
			</div>

			<?php } if($tipo == 2) { ?>

			<div class="x_panel">
				<div class="x_title">
					<h2>Nuevo tipo de usuario <small>Complete los campos</small></h2>
					<ul class="nav navbar-right panel_toolbox">
						<li class="chevron-up-right">
							<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
						</li>
					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="x_content">
					<form id="form-type-user" class="form-horizontal form-label-left">
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="description-type">Descripción <span class="required">*</span></label>
							<div class="col-md-6 col-sm-6 col-xs-12">
								<input type="text" id="description-type" name="description-type" required="required" placeholder="" class="form-control col-md-7 col-xs-12">
							</div>
						</div>
						<div class="ln_solid"></div>
						<div class="form-group">
							<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
								<button class="btn btn-primary" id="btn-reset-type-user" type="reset">Limpiar</button>
								<button class="btn btn-success" id="btn-guardar-type-user" type="button">Guardar</button>
							</div>
						</div>
					</form>
				</div>
			</div>

			<div class="x_panel">
				<div class="x_title">
					<h2>Lista de tipos de usuarios <small>&nbsp;</small></h2>
					<ul class="nav navbar-right panel_toolbox">
						<li class="chevron-up-right">
							<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
						</li>
					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="x_content">					
					<table id="table-type-user" class="table table-striped table-bordered" cellspacing="0" width="100%">
				        <thead>
				            <tr>
				            	<th>N°</th>
				                <th>Descripción</th>
				                <th>Fecha Registro</th>
				                <th>Estado</th>
				                <th>Acciones</th>
				            </tr>
				        </thead>
				        <tbody>
				            <tr>
				            	<td class="td-center">1</td>
				                <td class="td-center">Edinburgh</td>
				                <td class="td-center">2011/04/25</td>
				                <td class="td-center">Habilitado</td>
				                <td class="td-center">
									<button class="btn btn-default" id="" type="button"><i class="glyphicon glyphicon-pencil"></i></button>
				                	<button class="btn btn-default" id="" type="button"><i class="glyphicon glyphicon-remove"></i></button>
				                </td>
				            </tr>
				        </tbody>
				    </table>
					<script>
					  	$(document).ready(function() {
							$('#table-type-user').DataTable();
					  	});
					</script>
				</div>
			</div>

			<?php } ?>

		</div>
	</div>
</div>